language: php

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '7.1'

    - os: linux
      php: '7.2'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - composer check
