name: build

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

     - name: Run test suite
       run: composer check
